FROM centos:6.6
MAINTAINER cza
RUN groupadd web \
    && mkdir -p /opt/weblogic \
    && useradd -g web -m -d /opt/weblogic weblogic \
    && /bin/echo 'root:123456'|chpasswd \
    && /bin/echo 'weblogic:weblogic'|chpasswd \
    && chown -R weblogic:web /opt/weblogic/ \
    && curl -o /jdk-7u79-linux-x64.rpm http://192.168.3.99:7070/ccc/weblogic/jdk-7u79-linux-x64.rpm \
    && rpm -ivh /jdk-7u79-linux-x64.rpm \
    && rm -rf /jdk-7u79-linux-x64.rpm \
    && /bin/sed -i 's/securerandom.source=file:\/dev\/urandom/securerandom.source=file:\/dev\/.\/urandom/g' /usr/java/jdk1.7.0_79/jre/lib/security/java.security
ENV JAVA_HOME /usr/java/jdk1.7.0_79 \
    JRE_HOME /usr/java/jdk1.7.0_79/jre \
    CLASSPATH $CLASSPATH:$JAVA_HOME/lib:$JAVA_HOME/jre/lib \
    PATH $JAVA_HOME/bin:$JRE_HOME/bin:$PATH
COPY oraInst.loc /opt/weblogic/oraInst.loc
COPY wls.rsp /opt/weblogic/wls.rsp
COPY create_domain.rsp /opt/weblogic/create_domain.rsp
RUN chmod 777 /opt/weblogic/create_domain.rsp \
    && chmod 777 /opt/weblogic/wls.rsp \
    && chmod 777 /opt/weblogic/oraInst.loc
USER weblogic
RUN curl -o /opt/weblogic/wls_121200.jar http://192.168.3.99:7070/ccc/weblogic/wls_121200.jar \
    && java -jar /opt/weblogic/wls_121200.jar -silent -responseFile /opt/weblogic/wls.rsp -invPtrLoc /opt/weblogic/oraInst.loc \
    && mkdir -p /opt/weblogic/Oracle/Middleware/user_projects/domains/base_domain/ \
    && bash /opt/weblogic/Oracle/Middleware/wlserver/common/bin/config.sh -mode=silent -silent_script=/opt/weblogic/create_domain.rsp -logfile=/opt/weblogic/create_domain.log \
    && rm -rf /opt/weblogic/wls_121200.jar /opt/weblogic/wls.rsp /opt/weblogic/oralnst.loc  /opt/weblogic/create_domain.rsp
WORKDIR /opt/weblogic/Oracle/Middleware/user_projects/domains/base_domain
EXPOSE 7001 8001
CMD bash /opt/weblogic/Oracle/Middleware/user_projects/domains/base_domain/bin/startWebLogic.sh
